package com.YaNan.frame.hibernate.database.DBInterface;

public interface mySqlInterface {
	public static final String COLUMN_TYPE_INT = "INT";
	public static final String COLUMN_TYPE_TINYINT = "TINYINT";
	public static final String COLUMN_TYPE_SMALLINT = "SMALLINT";
	public static final String COLUMN_TYPE_MEDIUMINT = "MEDIUMINT";
	public static final String COLUMN_TYPE_INTEGER = "INTEGER";
	public static final String COLUMN_TYPE_BIGINT = "BIGINT";
	public static final String COLUMN_TYPE_BIT = "BIT";
	public static final String COLUMN_TYPE_REAL = "REAL";
	public static final String COLUMN_TYPE_DOUBLE = "DOUBLE";
	public static final String COLUMN_TYPE_FLOAT = "FLOAT";
	public static final String COLUMN_TYPE_DECIMAL = "DECIMAL";
	public static final String COLUMN_TYPE_NUMERIC = "NUMERIC";
	public static final String COLUMN_TYPE_CHAR = "CHAR";
	public static final String COLUMN_TYPE_VARCHAR = "VARCHAR";
	public static final String COLUMN_TYPE_DATE = "DATE";
	public static final String COLUMN_TYPE_TIME = "TIME";
	public static final String COLUMN_TYPE_YEAR = "YEAR";
	public static final String COLUMN_TYPE_TIMESTAMP = "TIMESTAMP";
	public static final String COLUMN_TYPE_DATETIME = "DATEMITE";
	public static final String COLUMN_TYPE_TINYBLOB = "TINYBLOB";
	public static final String COLUMN_TYPE_BLOB = "BLOB";
	public static final String COLUMN_TYPE_MEDIUMBLOB = "MEDIUMBLOB";
	public static final String COLUMN_TYPE_LONGBLOB = "LONGBLOB";
	public static final String COLUMN_TYPE_TINYTEXT = "TINYTEXT";
	public static final String COLUMN_TYPE_TEXT = "TEXT";
	public static final String COLUMN_TYPE_MEDIUMTEXT = "MEDIUMTEXT";
	public static final String COLUMN_TYPE_LONGTEXT = "LONGTEXT";
	public static final String COLUMN_TYPE_ENUM = "ENUM";
	public static final String COLUMN_TYPE_SET = "SET";
	public static final String COLUMN_TYPE_BINARY = "BINARY";
	public static final String COLUMN_TYPE_VARBINARY = "VARBINARY";
	public static final String COLUMN_TYPE_POINT = "POINT";
	public static final String COLUMN_TYPE_LINESTRING = "LINESTRING";
	public static final String COLUMN_TYPE_POLYGON = "POLYGON";
	public static final String COLUMN_TYPE_GEOMETRY = "GEOMETRY";
	public static final String COLUMN_TYPE_MULTIPOINT = "MULTIPOINT";
	public static final String COLUMN_TYPE_MULTILINESTRING = "MULTILINESTRING";
	public static final String COLUMN_TYPE_MULTIPOLYGON = "MULTIPOLYGON";
	public static final String COLUMN_TYPE_GEOMETRYCOLLECTION = "GEOMETRYCOLLECTION";
	public static final String INDEX_TYPE_NORMAL = "NORMAL";
	public static final String INDEX_TYPE_UNIQUE = "UNIQUE";
	public static final String INDEX_TYPE_FULLTEXT = "FULL TEXT";
	public static final String INDEX_METHOD_BTREE = "BTREE";
	public static final String INDEX_METHOD_HASH = "HASH";
	public static final String REFKEY_DELETE_RESTRICT = "RESTRICT";
	public static final String REFKEY_DELETE_NOACTION = "NO ACTION";
	public static final String REFKEY_DELETE_CASCADE = "CASCADE";
	public static final String REFKEY_DELETE_SETNULL = "SET NULL";
	public static final String REFKEY_UPDATE_RESTRICT = "RESTRICT";
	public static final String REFKEY_UPDATE_NOACTION = "NO ACTION";
	public static final String REFKEY_UPDATE_CASCADE = "CASCADE";
	public static final String REFKEY_UPDATE_SETNULL = "SET NULL";
	public static final String TRIG_ACTION_BEFORE = "BEFORE";
	public static final String TRIG_ACTION_AFTER = "AFTER";
	/**
	 * mysql some final variable
	 */
	public static final String User = "username";
	public static final String Password = "password";
	public static final String Port = "port";
	public static final String Scheme = "scheme";
	public static final String Driver = "driver";
	public static final String Name = "name";
	public static final String Type = "type";
	public static final String Host = "host";
	public static final String Encoding = "utf-8";
	public static final String Tabs = "tabs";
}